/*
 * This file is generated by jOOQ.
 */
package org.example.mnpg.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OperatorDO implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String name;
    private String tel;
    private String addr;
    private String permissionLevel;

    public OperatorDO() {}

    public OperatorDO(OperatorDO value) {
        this.id = value.id;
        this.name = value.name;
        this.tel = value.tel;
        this.addr = value.addr;
        this.permissionLevel = value.permissionLevel;
    }

    public OperatorDO(
        String id,
        String name,
        String tel,
        String addr,
        String permissionLevel
    ) {
        this.id = id;
        this.name = name;
        this.tel = tel;
        this.addr = addr;
        this.permissionLevel = permissionLevel;
    }

    /**
     * Getter for <code>mnpg.operator.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>mnpg.operator.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>mnpg.operator.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>mnpg.operator.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>mnpg.operator.tel</code>.
     */
    public String getTel() {
        return this.tel;
    }

    /**
     * Setter for <code>mnpg.operator.tel</code>.
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * Getter for <code>mnpg.operator.addr</code>.
     */
    public String getAddr() {
        return this.addr;
    }

    /**
     * Setter for <code>mnpg.operator.addr</code>.
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * Getter for <code>mnpg.operator.permission_level</code>.
     */
    public String getPermissionLevel() {
        return this.permissionLevel;
    }

    /**
     * Setter for <code>mnpg.operator.permission_level</code>.
     */
    public void setPermissionLevel(String permissionLevel) {
        this.permissionLevel = permissionLevel;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OperatorDO other = (OperatorDO) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.tel == null) {
            if (other.tel != null)
                return false;
        }
        else if (!this.tel.equals(other.tel))
            return false;
        if (this.addr == null) {
            if (other.addr != null)
                return false;
        }
        else if (!this.addr.equals(other.addr))
            return false;
        if (this.permissionLevel == null) {
            if (other.permissionLevel != null)
                return false;
        }
        else if (!this.permissionLevel.equals(other.permissionLevel))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.tel == null) ? 0 : this.tel.hashCode());
        result = prime * result + ((this.addr == null) ? 0 : this.addr.hashCode());
        result = prime * result + ((this.permissionLevel == null) ? 0 : this.permissionLevel.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OperatorDO (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(tel);
        sb.append(", ").append(addr);
        sb.append(", ").append(permissionLevel);

        sb.append(")");
        return sb.toString();
    }
}
