/*
 * This file is generated by jOOQ.
 */
package io.micronaut.db;


import io.micronaut.db.tables.TOperator;
import io.micronaut.db.tables.records.OperatorRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * mnpg.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OperatorRecord> OPERATOR_PKEY = Internal.createUniqueKey(TOperator.OPERATOR, DSL.name("operator_pkey"), new TableField[] { TOperator.OPERATOR.ID }, true);
}
