/*
 * This file is generated by jOOQ.
 */
package org.example.mnpg.db;


import java.util.Arrays;
import java.util.List;

import org.example.mnpg.db.tables.TOperationLog;
import org.example.mnpg.db.tables.TOperator;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mnpg extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mnpg</code>
     */
    public static final Mnpg MNPG = new Mnpg();

    /**
     * The table <code>mnpg.operation_log</code>.
     */
    public final TOperationLog OPERATION_LOG = TOperationLog.OPERATION_LOG;

    /**
     * The table <code>mnpg.operator</code>.
     */
    public final TOperator OPERATOR = TOperator.OPERATOR;

    /**
     * No further instances allowed
     */
    private Mnpg() {
        super("mnpg", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            TOperationLog.OPERATION_LOG,
            TOperator.OPERATOR
        );
    }
}
