/*
 * This file is generated by jOOQ.
 */
package org.example.mnpg.db;


import org.example.mnpg.db.tables.TOperationLog;
import org.example.mnpg.db.tables.TOperator;


/**
 * Convenience access to all tables in mnpg.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mnpg.operation_log</code>.
     */
    public static final TOperationLog OPERATION_LOG = TOperationLog.OPERATION_LOG;

    /**
     * The table <code>mnpg.operator</code>.
     */
    public static final TOperator OPERATOR = TOperator.OPERATOR;
}
